version: "3"

services:
  ifnti_nginx:
    container_name: web
    build: ./nginx/
    restart: unless-stopped
    ports:
      - "81:80"
    depends_on:
      - ifnti_app
    links:
      - ifnti_app
    volumes:
      - data:/app
    networks:
      - ifnti
  ifnti_app:
    container_name: ifnti_app
    build: ./ifnti_app/
    restart: unless-stopped
    volumes:
      - data:/app
    # extra_hosts:
    #   - "host_localhost:192.168.60.62"
    depends_on:
      - db
    networks:
      - ifnti
  db:
    container_name: db
    image: postgres
    ports:
      - 5434:5432
    expose:
      - 5432
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=ifnti
      - POSTGRES_PASSWORD=ifnti
      - POSTGRES_DB=ifnti
    networks:
      - ifnti

volumes:
  data:
  db_data:

networks:
    ifnti:
      driver: bridge
