# Generated by Django 4.1.13 on 2023-12-22 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_matiere_abbreviation'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='professeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.enseignant'),
        ),
    ]
