# Generated by Django 4.1.13 on 2024-01-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_remove_planning_intervalle_planning_datedebut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='intervalle',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
