# Generated by Django 4.1.13 on 2023-12-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='abbreviation',
            field=models.CharField(default='Short', max_length=10),
        ),
    ]
