# Generated by Django 5.0.1 on 2024-01-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='abbreviation',
            field=models.CharField(default='Short', max_length=10),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='anneebac2',
            field=models.IntegerField(blank=True, default=2024, null=True, verbose_name='Année d’obtention du BAC 2'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='anneeentree',
            field=models.IntegerField(blank=True, default=2024, null=True, verbose_name='Promotion'),
        ),
    ]
