# Generated by Django 4.2.4 on 2023-11-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='salaireBrut',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Salaire Brut'),
        ),
    ]
