# Generated by Django 4.2.4 on 2023-12-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='autres_nature_conges',
            field=models.CharField(max_length=330, null=True, verbose_name='Nature des congés'),
        ),
        migrations.AlterField(
            model_name='conge',
            name='nature',
            field=models.CharField(choices=[('Congé annuel', 'Congé annuel'), ('Congé de maternité', 'Congé de maternité'), ('Congé de paternité', 'Congé de paternité'), ('Autres', 'Autres')], max_length=30, verbose_name='Nature des congés'),
        ),
    ]
