# Generated by Django 4.2.4 on 2023-12-22 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_conge_autres_nature_conges_alter_conge_nature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conge',
            name='autres_nature_conges',
        ),
    ]
