# Generated by Django 4.2.7 on 2023-12-04 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_correspondancemaquette'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correspondancemaquette',
            old_name='nouveau',
            new_name='nouvelle',
        ),
    ]
