# Generated by Django 4.2.4 on 2023-12-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_conge_autres_nature_conges'),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='autre_nature',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Autre nature des congés'),
        ),
    ]
