# Generated by Django 4.2.7 on 2023-12-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_nouveau_correspondancemaquette_nouvelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondancemaquette',
            name='ancienne',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='correspondancemaquette',
            name='nouvelle',
            field=models.CharField(blank=True, null=True),
        ),
    ]
