# Generated by Django 5.0.1 on 2024-01-11 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_matiere_abbreviation'),
        ('main', '0002_matiere_abbreviation_alter_etudiant_anneebac2_and_more'),
        ('main', '0004_conge_autre_nature'),
    ]

    operations = [
    ]
