# Generated by Django 4.2.4 on 2024-01-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_matiere_abbreviation'),
        ('main', '0004_conge_autre_nature'),
    ]

    operations = [
    ]
