# Generated by Django 4.1.13 on 2024-01-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_matiere_abbreviation'),
        ('main', '0004_conge_autre_nature'),
    ]

    operations = [
    ]
