# Generated by Django 4.2.4 on 2024-01-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_merge_20240108_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaire',
            name='is_irpp',
        ),
        migrations.RemoveField(
            model_name='salaire',
            name='is_tcs',
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='anneebac2',
            field=models.IntegerField(blank=True, default=2024, null=True, verbose_name='Année d’obtention du BAC 2'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='anneeentree',
            field=models.IntegerField(blank=True, default=2024, null=True, verbose_name='Promotion'),
        ),
    ]
