# Generated by Django 4.2.4 on 2024-01-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_salaire_is_irpp_remove_salaire_is_tcs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='nombre_de_personnes_en_charge',
            field=models.IntegerField(default=0, verbose_name='Nombre de personne pris en charge'),
        ),
    ]
