# Generated by Django 4.2.4 on 2024-01-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_personnel_nombre_de_personnes_en_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='nombre_de_personnes_en_charge',
            field=models.IntegerField(default=0, verbose_name='Nbre de pers pris en charge'),
        ),
    ]
